### ISSUE TITLE
level 4 typo bug

### ISSUE THREAD

**Issue by mustucontractor** [EnigmaDragons/ProjectBitVault#331]
first dialogue in level 4 has 'favour' spelt wrong. favor is used in American English however favour is globally accepted.

**Comment by SilasReinagel** [comment]
"Favour is the older spelling of the same word. It was considered correct until recently, but now favor is the preferred spelling in American English, so much so that favour is considered a spelling error. In British English, however, favour is still preferred."

Favor is the preferred spelling. Not going to change this.
